server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/code-fusheng/springcloud.git
          searchPaths: config
          username: 2561035977@qq.com
          password: github1314520
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
